import './globals.css'
export const metadata = { title: 'AI Generated Site', description: 'Generated by Multi-Agent Builder' }
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}