import './globals.css'

export const metadata = {
  title: 'AI Generated Site',
  description: 'Generated by AI Website Builder',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}